over_roasted/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include(('recipes.urls', 'recipes'), namespace='recipes')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

recipes/urls.py
# Django
from django.urls import path

# Views
from recipes import views

urlpatterns = [
    path(
        route='',
        view=views.RecipeFeedView.as_view(),
        name='feed'
    ),
    path(
        route='new/',
        view=views.CreateRecipeView.as_view(),
        name='create'
    ),
    path(
        route='vote/',
        view=views.vote_view,
        name='vote'
    ),
    path(
        route='results/',
        view=views.results_view,
        name='results'
    )
]

users/urls.py
# Django
from django.urls import path

# View
from users import views
 
 
urlpatterns = [
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head_content %}{% endblock %}
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" 
     rel="stylesheet" 
     integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" 
     crossorigin="anonymous">
  </head>
  <body>
    {% include "nav.html" %}
    <main class="container">
        <div class="starter-template text-center py-5 px-3">
          {% block container %}{% endblock%}
        </div>
      
      </main>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">OverRoasted</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "recipes:feed" %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "recipes:create" %}">Create a new recipe</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">----</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "recipes:results" %}">Wanna see voting results?</a>
          </li>
        </ul>
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="/users/logout/">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>