over_roasted/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include(('recipes.urls', 'recipes'), namespace='recipes')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

recipes/urls.py
# Django
from django.urls import path

# Views
from recipes import views

urlpatterns = [
    path(
        route='',
        view=views.RecipeFeedView.as_view(),
        name='feed'
    ),
    path(
        route='new/',
        view=views.CreateRecipeView.as_view(),
        name='create'
    ),
    path(
        route='vote/',
        view=views.vote_view,
        name='vote'
    ),
    path(
        route='results/',
        view=views.results_view,
        name='results'
    )
]

users/urls.py
# Django
from django.urls import path

# View
from users import views
 
 
urlpatterns = [
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
]

recipes/models.py
#Django
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

# Models
from django.contrib.auth.models import User

# Utils
from datetime import timedelta


class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=200, unique=True)
    body = models.CharField(max_length=200)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title} by @{self.user.username}'

    def save(self, *args, **kwargs):
        user = self.user
        last_creation = user.recipe_set.all().last().created
        if last_creation < timezone.now()-timedelta(minutes=5):
             super(Recipe, self).save(*args, **kwargs)
        else:
            raise ValidationError(_('You can create a recipe every 5 minutes!'))

    @property
    def count_votes(self):
        return self.reciperanking_set.all().count()

    @property
    def sum_votes(self):
        ranking = self.reciperanking_set.all()
        ranks = [r.rank for r in ranking]
        return sum(ranks)
    
    @property
    def sum_votes_last_5_min(self):
        five_min_ago = timezone.now() - timedelta(minutes=5)
        ranking = self.reciperanking_set.filter(created__gte=five_min_ago)
        ranks = [r.rank for r in ranking]
        return sum(ranks)

    @property
    def sum_votes_last_hour(self):
        hour_ago = timezone.now() - timedelta(hours=1)
        ranking = self.reciperanking_set.filter(created__gte=hour_ago)
        ranks = [r.rank for r in ranking]
        return sum(ranks)

    @property
    def sum_votes_last_day(self):
        day_ago = timezone.now() - timedelta(days=1)
        ranking = self.reciperanking_set.filter(created__gte=day_ago)
        ranks = [r.rank for r in ranking]
        return sum(ranks)


class RecipeRanking(models.Model):
    SUPER_BAD = '-5'
    BAD = '-2'
    NOT_OK = '-1'
    OK = '+1'
    GOOD = '+2'
    SUPER_GOOD = '+5'
    RANKING_CHOICES = [
        (SUPER_BAD, -5),
        (BAD, -2),
        (NOT_OK, -1),
        (OK, 1),
        (GOOD, 2),
        (SUPER_GOOD, 5),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    rank = models.FloatField(max_length=2, choices=RANKING_CHOICES)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.username} Recipe: {self.recipe.title} Rank: {self.rank}'

    def save(self, *args, **kwargs):
        user = self.user
        recipe = self.recipe
        last_creation = recipe.reciperanking_set.all().last().created
        # If in the last 2 min, we havent't created a recipe
        if last_creation < timezone.now()-timedelta(minutes=2):
             super(RecipeRanking, self).save(*args, **kwargs)
        else:
            raise ValidationError(_('You can vote a recipe every 2 minutes!'))

recipes/forms.py
#Django
from django import forms

#Models
from recipes.models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('user', 'title', 'body')

recipes/views.py
#Django
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.db.models import Count
from django.utils import timezone

#Forms
from recipes.forms import RecipeForm

#Models
from recipes.models import Recipe, RecipeRanking
from django.contrib.auth.models import User

# Utils
from datetime import timedelta
from recipes.utils import *
from statistics import mean


class RecipeFeedView(LoginRequiredMixin, ListView):
    template_name = 'recipes/feed.html'
    model = Recipe
    ordering = ('?',)
    paginate_by = 1
    context_object_name = 'recipes'

    def get_queryset(self):
        return Recipe.objects.order_by('?')


class CreateRecipeView(LoginRequiredMixin, CreateView):
    template_name = 'recipes/new.html'
    form_class = RecipeForm
    success_url = reverse_lazy('recipes:feed')

    def get_context_data(self, **kwargs):
        """Add user and profile to context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


def vote_view(request):
    if request.POST:
        recipe_id = request.POST['recipe_id']
        rate_tag = request.POST['rate']
        username = request.user.username
    
        recipe = Recipe.objects.get(id=recipe_id)
        user = User.objects.get(username=username)

        # import pdb; pdb.set_trace()
        RecipeRanking.objects.create(
            user=user,
            recipe=recipe,
            rank=rate_tag
        )
    return redirect(request.META.get('HTTP_REFERER'))


def results_view(request):
    '''
    functions:
    top_10(), top_10_last_5_min(), top_10_last_hour(), top_10_last_day(), comensal_exigente_score(u)
    are created in recipes/utils.py
    '''

    top10 = top_10() # Top 10 score
    top10_last_5_min = top_10_last_5_min()
    top10_last_hour = top_10_last_hour()
    top10_last_day = top_10_last_day()

    # Comensal mas exigente
    u_exigente_dict = {u:comensal_exigente_score(u) for u in User.objects.all()}
    u_exigente_dict_sorted = sorted(u_exigente_dict.items(), key=lambda x: x[1], reverse=True)
    u_exigente = next(iter(u_exigente_dict_sorted))[0]

    # Comensal menos exigente: El que menos ha votado
    u_votes_dict = {u:Recipe.objects.all().filter(user=u).count() for u in User.objects.all()}
    u_votes_dict_sorted = sorted(u_votes_dict.items(), key=lambda x: x[1])
    u_menos_exigente = next(iter(u_votes_dict_sorted))[0]

    # Render
    context = {}
    context['top10'] = top10
    context['top10_last_5_min'] = top10_last_5_min
    context['top10_last_hour'] = top10_last_hour
    context['top10_last_day'] = top10_last_day
    context['u_exigente'] = u_exigente
    context['u_menos_exigente'] = u_menos_exigente
    
    return render(request=request, template_name='recipes/results.html', context=context)








        


        

templates/recipes/feed.html
{% extends "base.html" %}
{% block head_content %}
    <title>OverRoasted recipes</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row">

            {% for recipe in recipes %}
                {% include "recipes/recipe_card.html" %}
            {% endfor %}
        </div>
    </div>
    {% include "pagination.html" %}
{% endblock %}

templates/recipes/new.html
{% extends "base.html" %}

{% block head_content %}
<title>Create new recipe</title>
{% endblock %}

{% block container %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Post a new recipe</h4>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    {# Website field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                        >
                        <input
                            class="form-control {% if form.body.errors %}is-invalid{% endif %}"
                            type="text"
                            name="body"
                            placeholder="body"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                            {% for error in form.body.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/recipes/recipe_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">
        <div class="media-body">
            <br><p style="margin-top: 5px;">{{ recipe.title }}</p></br>
            <p>{{ recipe.body }}</p>
        </div>
    </div>
    <p class="mt-1 ml-2" >
        <br>Votes:</br> {{ recipe.count_votes }} 
    </p>

    <h6>Vote this recipe</h1>
    <form action="{% url "recipes:vote" %}" method="POST">{% csrf_token %}
        <input type="checkbox" name="rate" value="-5">
        <label for="rate"> -5 </label>|
        <input type="checkbox" name="rate" value="-2">
        <label for="rate"> -2 </label>|
        <input type="checkbox" name="rate" value="-1">
        <label for="rate"> -1 </label>|
        <input type="checkbox" name="rate" value="+1">
        <label for="rate"> +1 </label>|
        <input type="checkbox" name="rate" value="+2">
        <label for="rate"> +2 </label>|
        <input type="checkbox" name="rate" value="+5">
        <label for="rate"> +5 </label>
        <button type="submit" name="recipe_id" value="{{ recipe.id }}">Vote</button>
    </form>

    <p class="ml-2 mt-0 mb-2">
        <b>{{ recipe.user }}</b> - <small>{{ recipe.created }}</small>
    </p>
</div>

templates/recipes/results.html
{% extends "base.html" %}
{% block head_content %}
    <title>OverRoasted results</title>
{% endblock%}

{% block container %}
    <div class="container">

        <div class="media pt-3 pl-3 pb-1">
            <div class="media-body">
                <br><p style="margin-top: 5px;">{{ recipe.title }}</p></br>
                <p>{{ recipe.body }}</p>
            </div>
        </div>

        <div class="row">
            <div class="media pt-3 pl-3 pb-1">
                <h2>Top 10</h2>
                {% for t10 in top10 %}
                    {{ t10 }} <br>
                {% endfor %}
            </div>
            <br>
            <div class="media pt-3 pl-3 pb-1">
                <h2>Top 10 last 5 minutes</h2>
                {% for t10_5 in top10_last_5_min %}
                    {{ t10_5 }} <br>
                {% endfor %}
            </div>
            <br>
            <div class="media pt-3 pl-3 pb-1">
                <h2>Top 10 last hour</h2>
                {% for t10_h in top10_last_hour %}
                    {{ t10_h }} <br>
                {% endfor %}
            </div>
            <br>
            <div class="media pt-3 pl-3 pb-1">
                <h2>Top 10 last day</h2>
                {% for t10_d in top10_last_day %}
                    {{ t10_d }} <br>
                {% endfor %}
            </div>
            <br>
            <div class="media pt-3 pl-3 pb-1">
                <h2>Usuario mas exigente</h2>
                    {{ u_exigente }}
            </div>
            <br>
            <div class="media pt-3 pl-3 pb-1">
                <h2>Usuario menos exigente</h2>
                <h5>El que menos ha votado</h5>
                    {{ u_exigente }}
            </div>
        </div>
    </div>
{% endblock %}