over_roasted/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include(('recipes.urls', 'recipes'), namespace='recipes')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

users/urls.py
# Django
from django.urls import path

# View
from users import views
 
 
urlpatterns = [
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
]

users/forms.py
#Django
from django import forms

#Models
from django.contrib.auth.models import User


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(
        max_length=70, 
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)

users/views.py
# Django
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.views.generic import FormView
from django.urls import reverse, reverse_lazy
from django.contrib.auth import logout

#Models
from django.contrib.auth.models import User

#Forms
from users.forms import SignupForm 


class SignupView(FormView):
    """Users sign up view."""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    #ver doc de FormView.
    #Sobreescribimos el form_valid para que guarde los datos
    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)

class LoginView(auth_views.LoginView):
    """Login view."""
    template_name = 'users/login.html'

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""
    template_name = 'users/logged_out.html'
    

templates/users/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  </head>
  <body>
    <main class="container">
        <div class="starter-template text-center py-5 px-3">
          {% block container %}{% endblock%}
        </div>
      
      </main>
  </body>
</html>

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
<title>OverRoasted sign in</title>
{% endblock%}

{% block container %}
    {% if form.errors %}
        <p class="alert alert-danger">
            Your username and password didn't match. Please try again.
        </p>
    {% endif%}
    <h1>Welcome to <br>OverRoasted app</br></h1>
    <!-- <p>Please, sign in before continue</p> -->
    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}
        <div>
            <input 
             type="text" 
             placeholder="Username" 
             name="username" />
        </div>
        <div>
            <input 
             type="password" 
             placeholder="Password" 
             name="password" />
        </div>
        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>
    </form>
    <p class="mt-4">
        Don't have an account yet? 
        <a href="{% url "users:signup" %}">Sign up here.</a>
    </p>
{% endblock %}

templates/users/logout.html
{% extends "users/base.html" %}

{% block head_content %}
<title>OverRoasted logout</title>
{% endblock%}

{% block container %}
    {% if form.errors %}
        <p class="alert alert-danger">
            Your username and password didn't match. Please try again.
        </p>
    {% endif%}
    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}
        <h1>Thanks for comming</h1>
        <p>See you next time!</p>
        <div>
            <input 
             type="text" 
             placeholder="Username" 
             name="username" />
        </div>
        <div>
            <input 
             type="password" 
             placeholder="Password" 
             name="password" />
        </div>
        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>
    </form>
    <p class="mt-4">
        Don't have an account yet? 
        <a href="{% url "users:signup" %}">Sign up here.</a>
    </p>
{% endblock %}

templates/users/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" 
             aria-current="page" 
             href="{% url "users:login" %}">
                Sign in
            </a>
          </li>
      </div>
    </div>
  </nav>

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>OverRoasted sign up</title>
{% endblock %}

{% block container %}
{% include "users/nav.html" %}
    <h1>Signup</h1>
    <form action="{% url 'users:signup' %}" method="POST">
        <div>
            {% csrf_token %}
            {{ form.as_p }}
        </div>
        <div>
            <button class="btn btn-primary btn-block mt-5" type="submit">
                Register!
            </button>
        </div>
    </form>
{% endblock container %}